/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package junit;
class SomeClass {

    public static int sum(int a, int b) {
        return a + b;
    }
    public static String getGreeting() {
        return "Hello World!";
    }



    public static void main(String[] args) {
        System.out.println(SomeClass.getGreeting());
    }
}
